version: "3.8"
services:
  web:
    image: frontend:1.0
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    image: backend:1.0
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
    restart: unless-stopped
    volumes: 
      - mongodb_data:/data/db
    environment: 
    - PUID=1000
    - PGID=1000  
    # uncomment following lines to access db locally
    ports:
    - 27017:27017
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
